services:
  - type: web
    name: tracky-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
